name: angular
type: service
from: nginx
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.13"
title: Nginx (Angular)
labels:
- angular
- nginx

build:
  connect: true
  boilerplates:
  - name: angular
    title: Angular boilerplate
    repo: https://github.com/wodby/angular-boilerplate
    branch: main
